CREATE TABLE Koie(
	KoieID VARCHAR(30) NOT NULL PRIMARY KEY,
	Adresse VARCHAR(30),
	Standard VARCHAR(30),
	Storrelse INT,
	Vedstatus INT,
	URL VARCHAR(120)
);

CREATE TABLE Reservasjon(
	ID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	Epost VARCHAR(45),
	DatoFra DATE,
	DatoTil DATE,
	ReservertKoieID VARCHAR(30) NOT NULL,
	FOREIGN KEY(ReservertKoieID)
		REFERENCES Koie (KoieID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Admin(
	Brukernavn VARCHAR(30) NOT NULL PRIMARY KEY,
	Passord VARCHAR(15) NOT NULL,
	Navn VARCHAR(30),
	Tlf VARCHAR(8),
	Epost VARCHAR(45)
);

CREATE TABLE Utstyr(
	UtstyrsID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(UtstyrsID),
	Navn VARCHAR(30),
	Innkjopsdato DATE,
	stat BOOLEAN,
	AdminID VARCHAR(30) NOT NULL,
	FOREIGN KEY(AdminID)
		REFERENCES Admin(Brukernavn)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FraktesTilID VARCHAR(30) NOT NULL,
	FOREIGN KEY(FraktesTilID)
		REFERENCES Koie(KoieID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Rapport(
	RapportID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(RapportID),
	Tekst VARCHAR(100),
	Gjenglemt VARCHAR(100),
	Vedstatus INT,
	KoieRapportID VARCHAR(30) NOT NULL,
	FOREIGN KEY(KoieRapportID)
		REFERENCES Koie (KoieID)
		ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE ErOdelagt(
	UtstyrsID INT NOT NULL,
	RapportID INT NOT NULL,
	PRIMARY KEY(UtstyrsID, RapportID),
	FOREIGN KEY (UtstyrsID)
		REFERENCES Utstyr (UtstyrsID)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (RapportID)
		REFERENCES Rapport (RapportID)
		ON UPDATE CASCADE ON DELETE CASCADE
);